#!/usr/bin/env python3
"""
Procedurally generate geometric watchfaces (no source artwork needed).

Each face is drawn with PIL at 4x supersampling, thresholded to pure 1-bit
(no dithering - it looks muddy on the 200x200 e-paper), and written to
../mywatchfaces/<name>.h in the same format image2cpp produces.

Usage:
    python3 generate_geometric.py            # write all faces
    python3 generate_geometric.py tie orion  # write only these
"""

import math
import random
import sys
from pathlib import Path

from PIL import Image, ImageDraw

W = 200          # display size
SS = 4           # supersample factor
OUT_DIR = Path(__file__).parent.parent / "mywatchfaces"


# ---------------------------------------------------------------------------
# Drawing helpers (all coordinates in 200px display space)
# ---------------------------------------------------------------------------

class Canvas:
    def __init__(self, black_bg=False):
        self.black_bg = black_bg
        self.img = Image.new("L", (W * SS, W * SS), 0 if black_bg else 255)
        self.d = ImageDraw.Draw(self.img)
        self.ink = 255 if black_bg else 0
        self.paper = 0 if black_bg else 255

    def _s(self, v):
        return v * SS

    def line(self, p1, p2, width=2, color=None):
        c = self.ink if color is None else color
        self.d.line([(p1[0] * SS, p1[1] * SS), (p2[0] * SS, p2[1] * SS)],
                    fill=c, width=int(width * SS))

    def polyline(self, pts, width=2, color=None, closed=False):
        c = self.ink if color is None else color
        pts = [(x * SS, y * SS) for x, y in pts]
        if closed:
            pts.append(pts[0])
        self.d.line(pts, fill=c, width=int(width * SS), joint="curve")

    def polygon(self, pts, fill=None, outline=None, width=2):
        pts = [(x * SS, y * SS) for x, y in pts]
        if fill is not None:
            self.d.polygon(pts, fill=fill)
        if outline is not None:
            self.d.line(pts + [pts[0]], fill=outline, width=int(width * SS), joint="curve")

    def circle(self, c, r, width=2, fill=None, outline=None):
        box = [(c[0] - r) * SS, (c[1] - r) * SS, (c[0] + r) * SS, (c[1] + r) * SS]
        if fill is not None:
            self.d.ellipse(box, fill=fill)
        if outline is not None:
            self.d.ellipse(box, outline=outline, width=int(width * SS))

    def disc(self, c, r, color=None):
        self.circle(c, r, fill=self.ink if color is None else color)

    def ring(self, c, r, width=2, color=None):
        self.circle(c, r, width=width, outline=self.ink if color is None else color)

    def sparkle(self, c, size, color=None, thin=0.22):
        """4-point star (diamond spikes)."""
        col = self.ink if color is None else color
        x, y = c
        t = size * thin
        pts = [(x, y - size), (x + t, y - t), (x + size, y), (x + t, y + t),
               (x, y + size), (x - t, y + t), (x - size, y), (x - t, y - t)]
        self.polygon(pts, fill=col)

    def wedge(self, c, r_in, r_out, a0, a1, color=None):
        col = self.ink if color is None else color
        pts = []
        steps = 12
        for i in range(steps + 1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((c[0] + r_out * math.cos(a), c[1] + r_out * math.sin(a)))
        for i in range(steps, -1, -1):
            a = math.radians(a0 + (a1 - a0) * i / steps)
            pts.append((c[0] + r_in * math.cos(a), c[1] + r_in * math.sin(a)))
        self.polygon(pts, fill=col)

    def to_bits(self):
        small = self.img.resize((W, W), Image.LANCZOS)
        bw = small.point(lambda v: 0 if v < 128 else 255, "1")
        return bw


def write_header(name, bw, face_cfg):
    """Write mywatchfaces/<name>.h in image2cpp format. bit=1 -> black."""
    px = bw.load()
    data = bytearray()
    for y in range(W):
        for x in range(0, W, 8):
            b = 0
            for i in range(8):
                if px[x + i, y] == 0:
                    b |= 0x80 >> i
            data.append(b)

    lines = []
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{v:02x}" for v in data[i:i + 16])
        lines.append("\t" + chunk + ("," if i + 16 < len(data) else ""))

    arr = f"epd_bitmap_{name}"
    body = "\n".join(lines)
    cfg = "\n".join(f"    {k} = {v};" for k, v in face_cfg)
    text = f"""// '{name}', 200x200px - generated by watchfaceutils/generate_geometric.py
const unsigned char {arr} [] PROGMEM = {{
{body}
}};

// Array of all bitmaps for convenience. (Total bytes used to store images in PROGMEM = {len(data)})
static const int {arr}_allArray_LEN = 1;
static const unsigned char* {arr}_allArray[1] = {{
\t{arr}
}};

struct WatchFace_{name} : public WatchFace {{
  WatchFace_{name}() {{
    bitmap = {arr};
{cfg}
  }}
}};
"""
    out = OUT_DIR / f"{name}.h"
    out.write_text(text)
    return out


# ---------------------------------------------------------------------------
# Faces
# ---------------------------------------------------------------------------

FACES = {}


def face(fn):
    FACES[fn.__name__] = fn
    return fn


@face
def tie():
    """TIE fighter, line art. Time below."""
    c = Canvas()
    cy = 80
    for cx in (36, 164):
        hexa = [(cx, 22), (cx + 16, 44), (cx + 16, 116), (cx, 138), (cx - 16, 116), (cx - 16, 44)]
        c.polygon(hexa, outline=c.ink, width=5)
        for p in hexa:
            c.line((cx, cy), p, width=2.5)
        c.disc((cx, cy), 5)
    # struts
    c.line((52, cy), (76, cy), width=7)
    c.line((124, cy), (148, cy), width=7)
    # cockpit ball + window
    c.disc((100, cy), 27, color=c.paper)
    c.ring((100, cy), 27, width=5)
    c.ring((100, cy), 11, width=3)
    for k in range(8):
        a = math.radians(k * 45)
        c.line((100 + 11 * math.cos(a), cy + 11 * math.sin(a)),
               (100 + 26 * math.cos(a), cy + 26 * math.sin(a)), width=2.5)
    return c, [
        ("layout", 1), ("noAMPM", "true"),
        ("text1x", -1), ("text1y", 74), ("text1font", "&StarJedi_DGRW20pt7b"),
        ("text2x", -1), ("text2y", 91), ("text2font", "&StarJedi_DGRW10pt7b"),
    ]


@face
def deathstar():
    """Death Star: sphere, superlaser dish, equatorial trench. Time inside."""
    c = Canvas()
    R = 90
    c.ring((100, 100), R, width=4)
    c.ring((66, 60), 27, width=3)
    c.ring((66, 60), 15, width=2)
    c.disc((66, 60), 3)
    # trench: two chords clipped to the sphere
    for y in (106, 112):
        half = math.sqrt(R * R - (y - 100) ** 2)
        c.line((100 - half, y), (100 + half, y), width=2)
    return c, [
        ("layout", 1), ("noAMPM", "true"),
        ("text1x", -1), ("text1y", 60), ("text1font", "&StarJedi_DGRW20pt7b"),
        ("text2x", -1), ("text2y", 77), ("text2font", "&StarJedi_DGRW10pt7b"),
    ]


@face
def hallows():
    """Deathly Hallows: triangle, circle, line. Time below."""
    c = Canvas()
    apex, bl, br = (100, 10), (32, 122), (168, 122)
    c.polygon([apex, br, bl], outline=c.ink, width=6)
    base = br[0] - bl[0]
    leg = math.hypot(base / 2, bl[1] - apex[1])
    area = 0.5 * base * (bl[1] - apex[1])
    r = area / ((base + 2 * leg) / 2)
    c.ring((100, bl[1] - r), r, width=6)
    c.line(apex, (100, bl[1]), width=6)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 66), ("text1font", "&HARRYP__20pt7b"),
        ("text2x", -1), ("text2y", 87), ("text2font", "&HARRYP__10pt7b"),
    ]


@face
def prism():
    """Dark Side of the Moon: prism on black, beam in, spectrum out. White text."""
    c = Canvas(black_bg=True)
    apex, bl, br = (100, 38), (46, 130), (154, 130)
    c.polygon([apex, br, bl], outline=c.ink, width=3)

    def left_edge_x(y):
        return apex[0] - (y - apex[1]) / (bl[1] - apex[1]) * (apex[0] - bl[0])

    def right_edge_x(y):
        return apex[0] + (y - apex[1]) / (br[1] - apex[1]) * (br[0] - apex[0])

    entry = (left_edge_x(96), 96)
    c.line((0, 108), entry, width=2)
    exit_ = (right_edge_x(92), 92)
    c.line(entry, exit_, width=2)
    for i in range(6):
        c.line(exit_, (200, 70 + i * 13), width=2)
    return c, [
        ("layout", 0),
        ("text1x", -1), ("text1y", 78),
        ("text1color", "GxEPD_WHITE"), ("text1font", "&CompactaBT20pt7b"),
        ("text2color", "GxEPD_WHITE"), ("text2font", "&CompactaBT10pt7b"),
    ]


@face
def orbit():
    """Concentric orbits with planets; time sits where the sun would be."""
    c = Canvas()
    for r in (62, 78, 94, 110, 126):
        c.ring((100, 100), r, width=1.5)
    planets = [(62, 205, 3.5), (78, 330, 5), (94, 50, 4.5), (110, 140, 6.5), (126, 290, 5.5)]
    for r, ang, size in planets:
        a = math.radians(ang)
        p = (100 + r * math.cos(a), 100 + r * math.sin(a))
        c.disc(p, size)
    # ringed planet on the 4th orbit
    a = math.radians(140)
    p = (100 + 110 * math.cos(a), 100 + 110 * math.sin(a))
    c.polyline([(p[0] - 12, p[1] + 3), (p[0] + 12, p[1] - 3)], width=2)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 41), ("text1font", "&CompactaBT20pt7b"),
        ("text2x", -1), ("text2y", 57), ("text2font", "&CompactaBT10pt7b"),
    ]


@face
def orion():
    """Orion on a black sky. White text at the bottom."""
    c = Canvas(black_bg=True)
    S = {
        "meissa": (100, 14, 2), "betelgeuse": (60, 40, 5), "bellatrix": (140, 38, 4),
        "alnitak": (86, 88, 3), "alnilam": (100, 84, 3), "mintaka": (114, 80, 3),
        "saiph": (76, 128, 3), "rigel": (136, 132, 5),
    }
    edges = [("meissa", "betelgeuse"), ("meissa", "bellatrix"), ("betelgeuse", "alnitak"),
             ("bellatrix", "mintaka"), ("alnitak", "alnilam"), ("alnilam", "mintaka"),
             ("alnitak", "saiph"), ("mintaka", "rigel")]
    for a, b in edges:
        c.line(S[a][:2], S[b][:2], width=1.2)
    # sword
    for p, s in (((98, 96), 1.5), ((97, 104), 2), ((96, 112), 1.5)):
        c.disc(p, s)
    for name, (x, y, s) in S.items():
        c.disc((x, y), s)
        if s >= 4:
            c.sparkle((x, y), s * 2.4, thin=0.16)
    rng = random.Random(7)
    for _ in range(28):
        x, y = rng.uniform(4, 196), rng.uniform(4, 150)
        if min(math.hypot(x - sx, y - sy) for sx, sy, _ in S.values()) > 12:
            c.disc((x, y), rng.choice((0.8, 0.8, 1.2)))
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 72),
        ("text1color", "GxEPD_WHITE"), ("text1font", "&ToughCookiesBold_owZ1d20pt7b"),
        ("text2x", -1), ("text2y", 90),
        ("text2color", "GxEPD_WHITE"), ("text2font", "&ToughCookiesBold_owZ1d10pt7b"),
    ]


@face
def kolam():
    """Kambi (chain) kolam border: dots with loops weaving around them."""
    c = Canvas()
    inset, rad = 13, 22
    lo, hi = inset, W - inset
    # rounded-rect path, sampled by arc length
    straight = (hi - lo) - 2 * rad
    segs = []  # (length, fn(t)->(x,y,nx,ny))
    corners = [((hi - rad, lo + rad), -90), ((hi - rad, hi - rad), 0),
               ((lo + rad, hi - rad), 90), ((lo + rad, lo + rad), 180)]
    lines = [((lo + rad, lo), (1, 0), (0, -1)), ((hi, lo + rad), (0, 1), (1, 0)),
             ((hi - rad, hi), (-1, 0), (0, 1)), ((lo, hi - rad), (0, -1), (-1, 0))]
    for (p0, d, n), (cc, a0) in zip(lines, corners):
        segs.append((straight, lambda t, p0=p0, d=d, n=n: (p0[0] + d[0] * t, p0[1] + d[1] * t, n[0], n[1])))
        arc = math.pi / 2 * rad
        def arcfn(t, cc=cc, a0=a0):
            a = math.radians(a0) + t / rad
            return (cc[0] + rad * math.cos(a), cc[1] + rad * math.sin(a), math.cos(a), math.sin(a))
        segs.append((arc, arcfn))
    total = sum(l for l, _ in segs)
    n_loops = 34
    s = total / n_loops
    amp = 7.5

    def at(t):
        t %= total
        for l, fn in segs:
            if t <= l:
                return fn(t)
            t -= l
        return segs[-1][1](segs[-1][0])

    steps = 1400
    up, dn = [], []
    for i in range(steps + 1):
        t = total * i / steps
        x, y, nx, ny = at(t)
        off = amp * math.sin(math.pi * t / s)
        up.append((x + nx * off, y + ny * off))
        dn.append((x - nx * off, y - ny * off))
    c.polyline(up, width=2)
    c.polyline(dn, width=2)
    for k in range(n_loops):
        x, y, _, _ = at(s * (k + 0.5))
        c.disc((x, y), 1.8)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 36), ("text1font", "&Caveat_VariableFont_wght20pt7b"),
        ("text2x", -1), ("text2y", 56), ("text2font", "&Caveat_VariableFont_wght10pt7b"),
    ]


@face
def vinyl():
    """Record with a label; time on the label."""
    c = Canvas()
    c.disc((100, 100), 97)
    for r in (56, 66, 76, 86, 93):
        c.ring((100, 100), r, width=0.8, color=c.paper)
    c.disc((100, 100), 47, color=c.paper)
    c.ring((100, 100), 44, width=1)
    return c, [
        ("layout", 1), ("noAMPM", "true"),
        ("text1x", -1), ("text1y", 41), ("text1font", "&CompactaBT20pt7b"),
        ("text2x", -1), ("text2y", 59), ("text2font", "&CompactaBT10pt7b"),
    ]


@face
def sunburst():
    """Alternating rays around a clear disc."""
    c = Canvas()
    R = 62
    n = 24
    for k in range(0, n, 2):
        a0 = k * 360 / n - 90
        c.wedge((100, 100), R + 4, 160, a0, a0 + 360 / n)
    c.ring((100, 100), R, width=3)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 40), ("text1font", "&Bootle_4B9l20pt7b"),
        ("text2x", -1), ("text2y", 57), ("text2font", "&Bootle_4B9l10pt7b"),
    ]


@face
def minimal():
    """Pure typography with a double border and a rule."""
    c = Canvas()
    c.polygon([(6, 6), (194, 6), (194, 194), (6, 194)], outline=c.ink, width=2.5)
    c.polygon([(11, 11), (189, 11), (189, 189), (11, 189)], outline=c.ink, width=1)
    c.line((60, 113), (140, 113), width=1.5)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 27), ("text1font", "&ToughCookiesBold_owZ1d30pt7b"),
        ("text2x", -1), ("text2y", 63), ("text2font", "&ToughCookiesBold_owZ1d15pt7b"),
    ]


@face
def moon():
    """Crescent moon and stars. Time below."""
    c = Canvas()
    c.disc((122, 66), 52)
    c.disc((142, 50), 46, color=c.paper)
    for p, s in (((38, 34), 9), ((72, 18), 5), ((26, 92), 6), ((60, 128), 4), ((176, 130), 5), ((150, 118), 3)):
        c.sparkle(p, s)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 74), ("text1font", "&DynaPuff_VariableFont_wdth_wght20pt7b"),
        ("text2x", -1), ("text2y", 90), ("text2font", "&DynaPuff_VariableFont_wdth_wght10pt7b"),
    ]


# ---------------------------------------------------------------------------
# Batch 2
# ---------------------------------------------------------------------------

@face
def glasses():
    """Harry's round glasses and the scar."""
    c = Canvas()
    for cx in (62, 138):
        c.ring((cx, 82), 30, width=5)
    c.line((92, 82), (108, 82), width=4)
    c.line((32, 82), (12, 72), width=4)
    c.line((168, 82), (188, 72), width=4)
    bolt = [(160, 6), (138, 34), (150, 34), (128, 66), (158, 30), (146, 30)]
    c.polygon(bolt, fill=c.ink)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 62), ("text1font", "&HARRYP__20pt7b"),
        ("text2x", -1), ("text2y", 85), ("text2font", "&HARRYP__10pt7b"),
    ]


@face
def snitch():
    """Golden Snitch: ball with a pair of wings."""
    c = Canvas()
    cx, cy, r = 100, 66, 24
    c.ring((cx, cy), r, width=4)
    for dy in (-7, 7):
        half = math.sqrt(r * r - dy * dy)
        c.line((cx - half, cy + dy), (cx + half, cy + dy), width=2)
    c.ring((cx, cy), 6, width=2)

    def wing(sign):
        pts = [(cx + sign * 22, cy - 10), (cx + sign * 50, cy - 34), (cx + sign * 82, cy - 46),
               (cx + sign * 92, cy - 38), (cx + sign * 74, cy - 22), (cx + sign * 88, cy - 18),
               (cx + sign * 68, cy - 4), (cx + sign * 82, cy + 4), (cx + sign * 58, cy + 12),
               (cx + sign * 22, cy + 10)]
        c.polygon(pts, outline=c.ink, width=3)
        c.line((cx + sign * 26, cy - 2), (cx + sign * 70, cy - 26), width=2)
        c.line((cx + sign * 28, cy + 4), (cx + sign * 64, cy - 8), width=2)
    wing(1)
    wing(-1)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 62), ("text1font", "&Neuton_Bold20pt7b"),
        ("text2x", -1), ("text2y", 82), ("text2font", "&Neuton_Bold10pt7b"),
    ]


@face
def lightsaber():
    """Lightsaber along the bottom, time above."""
    c = Canvas()
    y = 162
    # hilt
    c.polygon([(8, y - 9), (58, y - 9), (58, y + 9), (8, y + 9)], fill=c.ink)
    for x in range(14, 50, 8):
        c.line((x, y - 9), (x, y + 9), width=2, color=c.paper)
    c.polygon([(58, y - 12), (68, y - 12), (68, y + 12), (58, y + 12)], fill=c.ink)  # emitter
    # blade with a white core
    c.polygon([(68, y - 6), (190, y - 6), (196, y), (190, y + 6), (68, y + 6)], fill=c.ink)
    c.line((72, y), (188, y), width=2, color=c.paper)
    return c, [
        ("layout", 1), ("noAMPM", "true"),
        ("text1x", -1), ("text1y", 30), ("text1font", "&StarJedi_DGRW20pt7b"),
        ("text2x", -1), ("text2y", 50), ("text2font", "&StarJedi_DGRW10pt7b"),
    ]


@face
def rocket():
    """Tintin-style rocket with checkered skirt and fins."""
    c = Canvas()
    body = [(100, 6), (114, 26), (121, 50), (121, 94), (114, 104), (86, 104), (79, 94), (79, 50), (86, 26)]
    c.polygon(body, outline=c.ink, width=4)
    c.ring((100, 52), 9, width=3)
    # checker skirt
    for row, y0 in enumerate((72, 83)):
        for col, x0 in enumerate((81, 90.5, 100, 109.5)):
            if (row + col) % 2 == 0:
                c.polygon([(x0, y0), (x0 + 9.5, y0), (x0 + 9.5, y0 + 11), (x0, y0 + 11)], fill=c.ink)
    # fins
    c.polygon([(79, 80), (54, 112), (79, 104)], fill=c.ink)
    c.polygon([(121, 80), (146, 112), (121, 104)], fill=c.ink)
    # exhaust
    for x, l in ((93, 10), (100, 16), (107, 10)):
        c.line((x, 106), (x, 106 + l), width=3)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 65), ("text1font", "&BekingBold_1Gqdg20pt7b"),
        ("text2x", -1), ("text2y", 84), ("text2font", "&BekingBold_1Gqdg10pt7b"),
    ]


@face
def cassette():
    """Cassette tape: time above, date on the label."""
    c = Canvas()
    c.polygon([(12, 98), (188, 98), (188, 190), (12, 190)], outline=c.ink, width=4)
    c.polygon([(24, 106), (176, 106), (176, 130), (24, 130)], outline=c.ink, width=2)
    for cx in (64, 136):
        c.ring((cx, 154), 15, width=3)
        for k in range(6):
            a = math.radians(k * 60)
            c.line((cx + 8 * math.cos(a), 154 + 8 * math.sin(a)),
                   (cx + 14 * math.cos(a), 154 + 14 * math.sin(a)), width=2)
    c.polygon([(82, 146), (118, 146), (118, 162), (82, 162)], outline=c.ink, width=2)
    c.line((79, 154), (121, 154), width=1.5)
    c.polygon([(58, 190), (142, 190), (132, 176), (68, 176)], outline=c.ink, width=2)
    for x, y in ((20, 184), (180, 184), (20, 104), (180, 104)):
        c.disc((x, y), 2)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 20), ("text1font", "&Monster_AG20pt7b"),
        ("text2x", -1), ("text2y", 56), ("text2font", "&Monster_AG10pt7b"),
    ]


@face
def equalizer():
    """Equalizer bars along the bottom."""
    c = Canvas()
    heights = [32, 58, 84, 48, 100, 72, 112, 62, 90, 42, 68, 36]
    x = 12
    for h in heights:
        c.polygon([(x, 190 - h), (x + 10, 190 - h), (x + 10, 190), (x, 190)], fill=c.ink)
        for yy in range(190 - h + 6, 190, 7):  # segment gaps
            c.line((x, yy), (x + 10, yy), width=1.5, color=c.paper)
        x += 15
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 8), ("text1font", "&BADABB__20pt7b"),
        ("text2x", -1), ("text2y", 28), ("text2font", "&BADABB__10pt7b"),
    ]


@face
def mandala():
    """Eight-petal lotus frame; time in the centre."""
    c = Canvas()
    cx, cy = 100, 100

    def petal(angle, r1, r2, halfw, width=2.5, fill=None):
        pts = []
        for i in range(21):
            t = i / 20
            r = r1 + (r2 - r1) * t
            pts.append((r, halfw * math.sin(math.pi * t)))
        for i in range(20, -1, -1):
            t = i / 20
            r = r1 + (r2 - r1) * t
            pts.append((r, -halfw * math.sin(math.pi * t)))
        a = math.radians(angle)
        rot = [(cx + x * math.cos(a) - y * math.sin(a), cy + x * math.sin(a) + y * math.cos(a)) for x, y in pts]
        if fill:
            c.polygon(rot, fill=c.ink)
        else:
            c.polygon(rot, outline=c.ink, width=width)

    for k in range(8):
        petal(k * 45, 60, 98, 15)
    for k in range(8):
        petal(k * 45 + 22.5, 62, 80, 6, fill=True)
    c.ring((cx, cy), 58, width=2)
    for k in range(24):
        a = math.radians(k * 15)
        c.disc((cx + 53 * math.cos(a), cy + 53 * math.sin(a)), 1.5)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 41), ("text1font", "&Helloworld_ovvY020pt7b"),
        ("text2x", -1), ("text2y", 56), ("text2font", "&Helloworld_ovvY010pt7b"),
    ]


@face
def forest():
    """Pine silhouettes along the bottom, stars above."""
    c = Canvas()
    trees = [(16, 64), (44, 92), (72, 58), (100, 104), (128, 74), (156, 96), (184, 62)]
    for x, h in sorted(trees, key=lambda t: -t[1]):  # tall trees behind
        top = 190 - h
        tiers = []
        for tier in range(3):
            y0 = top + tier * h * 0.26
            y1 = top + (tier + 1) * h * 0.33
            w = h * (0.12 + 0.065 * tier)
            tiers.append([(x, y0), (x + w, y1), (x - w, y1)])
        trunk = [(x - 2.5, 190 - h * 0.05), (x + 2.5, 190 - h * 0.05), (x + 2.5, 192), (x - 2.5, 192)]
        for poly in tiers + [trunk]:  # white halo first, so this tree stands off the one behind it
            c.polygon(poly, outline=c.paper, width=3)
        for poly in tiers + [trunk]:
            c.polygon(poly, fill=c.ink)
    c.line((0, 191), (200, 191), width=3)
    for p, s in (((26, 24), 5), ((60, 12), 3), ((150, 18), 6), ((178, 40), 3), ((110, 8), 2.5)):
        c.sparkle(p, s)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 16), ("text1font", "&Neuton_Bold20pt7b"),
        ("text2x", -1), ("text2y", 33), ("text2font", "&Neuton_Bold10pt7b"),
    ]


@face
def dial():
    """Classic dial ring with hour ticks, digital time in the centre."""
    c = Canvas()
    cx, cy, R = 100, 100, 94
    c.ring((cx, cy), R, width=3)
    for k in range(60):
        a = math.radians(k * 6 - 90)
        if k % 15 == 0:
            ln, w = 14, 4
        elif k % 5 == 0:
            ln, w = 9, 2.5
        else:
            ln, w = 4, 1
        c.line((cx + (R - 3) * math.cos(a), cy + (R - 3) * math.sin(a)),
               (cx + (R - 3 - ln) * math.cos(a), cy + (R - 3 - ln) * math.sin(a)), width=w)
    c.disc((cx, cy + 34), 3)
    return c, [
        ("layout", 1),
        ("text1x", -1), ("text1y", 38), ("text1font", "&Neuton_Bold20pt7b"),
        ("text2x", -1), ("text2y", 55), ("text2font", "&Neuton_Bold10pt7b"),
    ]


@face
def waves():
    """Rolling waves along the bottom with a sun; time in the sky."""
    c = Canvas()
    c.ring((164, 100), 13, width=3)
    for k in range(12):
        a = math.radians(k * 30)
        c.line((164 + 18 * math.cos(a), 100 + 18 * math.sin(a)),
               (164 + 25 * math.cos(a), 100 + 25 * math.sin(a)), width=2.5)
    for i, (base, amp, period, phase) in enumerate(((132, 6, 46, 0), (150, 7, 52, 1.2), (168, 8, 58, 2.6), (186, 6, 50, 0.6))):
        pts = [(x, base + amp * math.sin(2 * math.pi * x / period + phase)) for x in range(-5, 206, 2)]
        c.polyline(pts, width=3 + i * 0.5)
    return c, [
        ("layout", 1),
        ("text1x", 6), ("text1y", 14), ("text1font", "&OctoberTwilight_Ooe615pt7b"),
        ("text2x", 6), ("text2y", 36), ("text2font", "&OctoberTwilight_Ooe610pt7b"),
    ]


# ---------------------------------------------------------------------------

def main(names):
    names = names or list(FACES)
    for n in names:
        canvas, cfg = FACES[n]()
        out = write_header(n, canvas.to_bits(), cfg)
        print(f"wrote {out}")


if __name__ == "__main__":
    main(sys.argv[1:])
