#!/usr/bin/env python3
"""
Regenerate the collection tables in docs/GALLERY.md and the collections line in
docs/README.md from the GROUPS list below. Everything outside the
<!-- gallery:start --> / <!-- gallery:end --> markers is left untouched.

Names prefixed with "!" are retired faces: kept as HTML comments, not counted.
Labels ending in "*" are generated by generate_geometric.py.
"""

import re
from pathlib import Path

ROOT = Path(__file__).parent.parent

GROUPS = [
    ("Star Wars Collection", [
        ("atat", "AT-AT"), ("atdp", "AT-DP"), ("b1", "B1 Battle Droid"), ("stormtrooper2", "Stormtrooper 2"),
        ("stormtrooper3_floyd", "Stormtrooper 3"), ("xwing", "X-Wing"), ("tie", "TIE Fighter*"),
        ("deathstar", "Death Star*"), ("lightsaber", "Lightsaber*"), ("r2d2", "R2-D2*"), ("falcon", "Millennium Falcon*"),
        ("vader", "Darth Vader*"), ("mando", "Mandalorian*"),
    ]),
    ("Harry Potter Collection", [
        ("harry934", "Harry Potter"), ("hogwarts", "Hogwarts"), ("hogwarts2", "Hogwarts 2"), ("hogwarts3", "Hogwarts 3"),
        ("hogwarts4", "Hogwarts 4"), ("sortinghat", "Sorting Hat"), ("hallows", "Deathly Hallows*"),
        ("glasses", "Glasses & Scar*"), ("snitch", "Golden Snitch*"), ("hedwig", "Hedwig*"),
    ]),
    ("Club Penguin Collection", [
        ("jitsu1", "Card Jitsu 1"), ("jitsu2", "Card Jitsu 2"), ("jitsu3", "Card Jitsu 3"), ("jitsu4", "Card Jitsu 4"),
        ("jitsu5", "Card Jitsu 5"), ("sensei", "Sensei"), ("herbert", "Herbert"), ("penguin", "Penguin*"),
    ]),
    ("Animals", [
        ("bird", "Bird"), ("bird2", "Bird 2"), ("!crow", "Crow"), ("dog", "Dog"), ("!giraffe1", "Giraffe"),
        ("macaw", "Macaw"), ("peacock", "Peacock"), ("peacock3", "Peacock 3"), ("zebra", "Zebra"), ("whale", "Whale*"), ("cat", "Cat*"),
    ]),
    ("Other Characters", [
        ("ben10", "Ben 10"), ("bugs", "Bugs Bunny"), ("!claw", "Claw"), ("claw2", "Claw 2"), ("claw3", "Claw 3"),
        ("tom", "Tom (Tom & Jerry)"), ("mikew", "Mike Wazowski"), ("sullivan", "Sulley"), ("pegasus", "Pegasus"),
        ("penguins", "Penguins of Madagascar"), ("penguin_beatles", "Penguin Beatles"), ("boodoor", "Boo's Door*"),
    ]),
    ("Horizon Zero Dawn", [
        ("walker", "Walker"), ("thunderjaw", "Thunderjaw*"), ("watcher", "Watcher*"), ("sawtooth", "Sawtooth*"),
        ("stormbird", "Stormbird*"), ("strider", "Strider*"),
    ]),
    ("Music & Entertainment", [
        ("guitar1", "Guitar 1"), ("guitar2", "Guitar 2"), ("ps", "PlayStation"), ("prism", "Prism (Dark Side of the Moon)*"),
        ("vinyl", "Vinyl*"), ("cassette", "Cassette*"), ("equalizer", "Equalizer*"), ("headphones", "Headphones*"),
    ]),
    ("Nature & Landscapes", [
        ("mountain1", "Mountain 1"), ("mountain2", "Mountain 2"), ("tree", "Tree"), ("forest", "Forest*"),
        ("waves", "Waves*"), ("moon", "Moon*"), ("balloon", "Hot-Air Balloon*"), ("lighthouse", "Lighthouse*"), ("sailboat", "Sailboat*"),
    ]),
    ("Space", [
        ("planets", "Planets"), ("saturn", "Saturn"), ("orbit", "Orbits*"), ("orion", "Orion*"), ("rocket", "Rocket*"),
        ("ufo", "UFO*"), ("astronaut", "Astronaut*"),
    ]),
    ("Cultural & Spiritual", [
        ("krishna", "Krishna"), ("thiruman", "Thiruman"), ("kolam", "Kolam*"), ("mandala", "Mandala*"), ("diya", "Diya*"), ("hari", "Hari (Tamil)*"),
    ]),
    ("Everyday Things", [
        ("coffee", "Coffee*"), ("bicycle", "Bicycle*"), ("camera", "Camera*"),
    ]),
    ("Abstract & Patterns", [
        ("h", "haricane8133"), ("harley", "Harley Davidson"), ("sunburst", "Sunburst*"), ("minimal", "Minimal*"), ("dial", "Dial*"),
    ]),
]


def cell(name, label):
    retired = name.startswith("!")
    name = name.lstrip("!")
    td = (f'    <td align="center" width="33%">\n'
          f'      <img src="../watchfaceutils/previews/{name}.png" width="200"/><br/>\n'
          f'      <b>{label}</b>\n'
          f'    </td>\n')
    return f"    <!-- {td.strip()} -->\n" if retired else td


def main():
    out, counts = [], []
    for title, faces in GROUPS:
        counts.append((title.replace(" Collection", ""), sum(1 for n, _ in faces if not n.startswith("!"))))
        out.append(f"## {title}\n\n<table>\n")
        for i in range(0, len(faces), 3):
            out.append("  <tr>\n" + "".join(cell(n, l) for n, l in faces[i:i + 3]) + "  </tr>\n")
        out.append("</table>\n\n")
    total = sum(c for _, c in counts)

    gal = ROOT / "docs" / "GALLERY.md"
    s = gal.read_text()
    s = re.sub(r"(<!-- gallery:start -->\n).*?(<!-- gallery:end -->)", lambda m: m.group(1) + "".join(out) + m.group(2), s, flags=re.S)
    s = re.sub(r"Browse all \d+ available", f"Browse all {total} available", s)
    s = re.sub(r"\*\*Total Watchfaces\*\*: \d+", f"**Total Watchfaces**: {total}", s)
    gal.write_text(s)

    readme = ROOT / "docs" / "README.md"
    t = readme.read_text()
    t = re.sub(r"\*\*Collections\*\*:.*", "**Collections**: " + " • ".join(f"{n} ({c})" for n, c in counts), t)
    t = re.sub(r"Browse all \d+ watchfaces", f"Browse all {total} watchfaces", t)
    t = re.sub(r"\d+\+ pre-configured", f"{total}+ pre-configured", t)
    t = re.sub(r"View All \d+ Watchfaces", f"View All {total} Watchfaces", t)
    readme.write_text(t)
    (ROOT / "README.md").write_text(re.sub(r"\(\d+ watchfaces\)", f"({total} watchfaces)", (ROOT / "README.md").read_text()))
    print(f"{total} watchfaces in {len(GROUPS)} collections")


if __name__ == "__main__":
    main()
